version: '3.8'

services:
  huinong-platform:
    build: .
    image: huinong-platform:latest
    container_name: huinong-platform
    ports:
      - "8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://${MYSQL_HOST}:3306/huinong_platform?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
      SPRING_DATASOURCE_USERNAME: ${MYSQL_USER}
      SPRING_DATASOURCE_PASSWORD: ${MYSQL_PASS}
      SPRING_REDIS_HOST: ${REDIS_HOST}
      SPRING_REDIS_PORT: ${REDIS_PORT}
      SPRING_RABBITMQ_HOST: ${RABBITMQ_HOST}
      SPRING_RABBITMQ_PORT: ${RABBITMQ_PORT}
      SPRING_RABBITMQ_USERNAME: ${RABBITMQ_USER}
      SPRING_RABBITMQ_PASSWORD: ${RABBITMQ_PASS}
      MINIO_ENDPOINT: http://${MINIO_HOST}:9000
      MINIO_ACCESS_KEY: ${MINIO_ACCESS_KEY}
      MINIO_SECRET_KEY: ${MINIO_SECRET_KEY}
      MINIO_BUCKET_NAME: huinong-upload
      MINIO_BUCKET_POLICY: public
      MINIO_PRESIGNED_EXPIRY_HOURS: 168
      MINIO_PRESIGNED_REFRESH_THRESHOLD: 24
      ALIBABA_CLOUD_ACCESS_KEY_ID: ${ALIYUN_SMS_KEY_ID}
      ALIBABA_CLOUD_ACCESS_KEY_SECRET: ${ALIYUN_SMS_KEY_SECRET}
    volumes:
      - ./logs:/app/logs
    restart: unless-stopped
    networks:
      - backend-network

networks:
  backend-network:
    driver: bridge
